c64_jmptbl = {

    0xe000: "		(exp continues)	EXP continued From BASIC ROM         ",
    0xe043: "	polyx	Series Evaluation                                ",
    0xe08d: "	rmulc	Constants for RND			                     ",
    0xe097: "	rnd	Perform [rnd]                                        ",
    0xe0f9: "	bioerr	Handle I/O Error in BASIC                        ",
    0xe10c: "	bchout	Output Character                                 ",
    0xe112: "	bchin	Input Character                                  ",
    0xe118: "	bckout	Set Up For Output                                ",
    0xe11e: "	bckin	Set Up For Input                                 ",
    0xe124: "	bgetin	Get One Character                                ",
    0xe12a: "	sys	Perform [sys]                                        ",
    0xe156: "	savet	Perform [save]                                   ",
    0xe165: "	verfyt	Perform [verify / load]                          ",
    0xe1be: "	opent	Perform [open]                                   ",
    0xe1c7: "	closet	Perform [close]                                  ",
    0xe1d4: "	slpara	Get Parameters For LOAD/SAVE                     ",
    0xe200: "	combyt	Get Next One Byte Parameter                      ",
    0xe206: "	deflt	Check Default Parameters                         ",
    0xe20e: "	cmmerr	Check For Comma                                  ",
    0xe219: "	ocpara	Get Parameters For OPEN/CLOSE                    ",
    0xe264: "	cos	Perform [cos]                                        ",
    0xe26b: "	sin	Perform [sin]                                        ",
    0xe2b4: "	tan	Perform [tan]                                        ",
    0xe2e0: "	pi2	Table of Trig Constants			                     ",
    0xe30e: "	atn	Perform [atn]                                        ",
    0xe33e: "	atncon	Table of ATN Constants			                 ",
    0xe37b: "	bassft	BASIC Warm Start [RUNSTOP-RESTORE]               ",
    0xe394: "	init	BASIC Cold Start                                 ",
    0xe3a2: "	initat	CHRGET For Zero-page                             ",
    0xe3ba: "	rndsed	RND Seed For zero-page			                 ",
    0xe3bf: "	initcz	Initialize BASIC RAM                             ",
    0xe422: "	initms	Output Power-Up Message                          ",
    0xe447: "	bvtrs	Table of BASIC Vectors (for 0300)	             ",
    0xe453: "	initv	Initialize Vectors                               ",
    0xe45f: "	words	Power-Up Message			                     ",
    0xe4ad: "	-	Patch for BASIC Call to CHKOUT                       ",
    0xe4b7: "	-	Unused Bytes For Future Patches		                 ",
    0xe4da: "	-	Reset Character Colour                               ",
    0xe4e0: "	-	Pause After Finding Tape File                        ",
    0xe4ec: "	-	RS-232 Timing Table -- PAL		                     ",
    0xe500: "	iobase	Get I/O Address                                  ",
    0xe505: "	screen	Get Screen Size                                  ",
    0xe50a: "	plot	Put / Get Row And Column                         ",
    0xe518: "	cint1	Initialize I/O                                   ",
    0xe544: "	-	Clear Screen                                         ",
    0xe566: "	-	Home Cursor                                          ",
    0xe56c: "	-	Set Screen Pointers                                  ",
    0xe59a: "	-	Set I/O Defaults (Unused Entry)                      ",
    0xe5a0: "	-	Set I/O Defaults                                     ",
    0xe5b4: "	lp2	Get Character From Keyboard Buffer                   ",
    0xe5ca: "	-	Input From Keyboard                                  ",
    0xe632: "	-	Input From Screen or Keyboard                        ",
    0xe684: "	-	Quotes Test                                          ",
    0xe691: "	-	Set Up Screen Print                                  ",
    0xe6b6: "	-	Advance Cursor                                       ",
    0xe6ed: "	-	Retreat Cursor                                       ",
    0xe701: "	-	Back on to Previous Line                             ",
    0xe716: "	-	Output to Screen                                     ",
    0xe72a: "	-	-unshifted characters-                               ",
    0xe7d4: "	-	-shifted characters-                                 ",
    0xe87c: "	-	Go to Next Line                                      ",
    0xe891: "	-	Output <CR>                                          ",
    0xe8a1: "	-	Check Line Decrement                                 ",
    0xe8b3: "	-	Check Line Increment                                 ",
    0xe8cb: "	-	Set Colour Code                                      ",
    0xe8da: "	-	Colour Code Table                                    ",
    0xe8ea: "	-	Scroll Screen                                        ",
    0xe965: "	-	Open A Space On The Screen                           ",
    0xe9c8: "	-	Move A Screen Line                                   ",
    0xe9e0: "	-	Syncronise Colour Transfer                           ",
    0xe9f0: "	-	Set Start of Line                                    ",
    0xe9ff: "	-	Clear Screen Line                                    ",
    0xea13: "	-	Print To Screen                                      ",
    0xea24: "	-	Syncronise Colour Pointer                            ",
    0xea31: "	-	Main IRQ Entry Point                                 ",
    0xea87: "	scnkey	Scan Keyboard                                    ",
    0xeadd: "	-	Process Key Image                                    ",
    0xeb79: "	-	Pointers to Keyboard decoding tables	             ",
    0xeb81: "	-	Keyboard 1 -- unshifted			DATA                 ",
    0xebc2: "	-	Keyboard 2 -- Shifted			DATA                 ",
    0xec03: "	-	Keyboard 3 -- Commodore			DATA                 ",
    0xec44: "	-	Graphics/Text Control                                ",
    0xec78: "	-	Keyboard 4 -- Control			DATA                 ",
    0xecb9: "	-	Video Chip Setup Table			DATA                 ",
    0xece7: "	-	Shift-Run Equivalent                                 ",
    0xecf0: "	-	Low Byte Screen Line Addresses		DATA             ",
    0xed09: "	talk	Send TALK Command on Serial Bus                  ",
    0xed0c: "	listn	Send LISTEN Command on Serial Bus                ",
    0xed40: "	-	Send Data On Serial Bus                              ",
    0xedad: "	-	Status #80 - device not present                      ",
    0xedb0: "	-	Status #03 - write timeout                           ",
    0xedb9: "	second	Send LISTEN Secondary Address                    ",
    0xedbe: "	-	Clear ATN                                            ",
    0xedc7: "	tksa	Send TALK Secondary Address                      ",
    0xedcc: "	-	Wait For Clock                                       ",
    0xeddd: "	ciout	Send Serial Deferred                             ",
    0xedef: "	untlk	Send UNTALK / UNLISTEN                           ",
    0xee13: "	acptr	Receive From Serial Bus                          ",
    0xee85: "	-	Serial Clock On                                      ",
    0xee8e: "	-	Serial Clock Off                                     ",
    0xee97: "	-	Serial Output 1                                      ",
    0xeea0: "	-	Serial Output 0                                      ",
    0xeea9: "	-	Get Serial Data And Clock In                         ",
    0xeeb3: "	-	Delay 1 ms                                           ",
    0xeebb: "	-	RS-232 Send                                          ",
    0xef06: "	-	Send New RS-232 Byte                                 ",
    0xef2e: "	-	'No DSR' / 'No CTS' Error                            ",
    0xef39: "	-	Disable Timer                                        ",
    0xef4a: "	-	Compute Bit Count                                    ",
    0xef59: "	-	RS-232 Receive                                       ",
    0xef7e: "	-	Set Up To Receive                                    ",
    0xef90: "	-	Process RS-232 Byte                                  ",
    0xefe1: "	-	Submit to RS-232                                     ",
    0xf00d: "	-	No DSR (Data Set Ready) Error                        ",
    0xf017: "	-	Send to RS-232 Buffer                                ",
    0xf04d: "	-	Input From RS-232                                    ",
    0xf086: "	-	Get From RS-232                                      ",
    0xf0a4: "	-	Serial Bus Idle                                      ",
    0xf0bd: "	-	Table of Kernal I/O Messages		DATA             ",
    0xf12b: "	-	Print Message if Direct                              ",
    0xf12f: "	-	Print Message                                        ",
    0xf13e: "	getin	Get a byte                                       ",
    0xf157: "	chrin	Input a byte                                     ",
    0xf199: "	-	Get From Tape / Serial / RS-232                      ",
    0xf1ca: "	chrout	Output One Character                             ",
    0xf20e: "	chkin	Set Input Device                                 ",
    0xf250: "	chkout	Set Output Device                                ",
    0xf291: "	close	Close File                                       ",
    0xf30f: "	-	Find File                                            ",
    0xf31f: "	-	Set File values                                      ",
    0xf32f: "	clall	Abort All Files                                  ",
    0xf333: "	clrchn	Restore Default I/O                              ",
    0xf34a: "	open	Open File                                        ",
    0xf3d5: "	-	Send Secondary Address                               ",
    0xf409: "	-	Open RS-232                                          ",
    0xf49e: "	load	Load RAM                                         ",
    0xf4b8: "	-	Load File From Serial Bus                            ",
    0xf533: "	-	Load File From Tape                                  ",
    0xf5af: "	-	Print SEARCHING                                   ",
    0xf5c1: "	-	Print Filename                                       ",
    0xf5d2: "	-	Print LOADING / VERIFYING                          ",
    0xf5dd: "	save	Save RAM                                         ",
    0xf5fa: "	-	Save to Serial Bus                                   ",
    0xf659: "	-	Save to Tape                                         ",
    0xf68f: "	-	Print SAVING                                       ",
    0xf69b: "	udtim	Bump Clock                                       ",
    0xf6dd: "	rdtim	Get Time                                         ",
    0xf6e4: "	settim	Set Time                                         ",
    0xf6ed: "	stop	Check STOP Key                                   ",
    0xf6fb: "	-	Output I/O Error Messages 'too many files'           ",
    0xf6fe: "	-	'file open'                                          ",
    0xf701: "	-	'file not open'                                      ",
    0xf704: "	-	'file not found'                                     ",
    0xf707: "	-	'device not present'                                 ",
    0xf70a: "	-	'not input file'                                     ",
    0xf70d: "	-	'not output file'                                    ",
    0xf710: "	-	'missing filename'                                   ",
    0xf713: "	-	'illegal device number'                              ",
    0xf72d: "	-	Find Any Tape Header                                 ",
    0xf76a: "	-	Write Tape Header                                    ",
    0xf7d0: "	-	Get Buffer Address                                   ",
    0xf7d7: "	-	Set Buffer Stat / End Pointers                       ",
    0xf7ea: "	-	Find Specific Tape Header                            ",
    0xf80d: "	-	Bump Tape Pointer                                    ",
    0xf817: "	-	Print PRESS PLAY ON TAPE                           ",
    0xf82e: "	-	Check Tape Status                                    ",
    0xf838: "	-	Print PRESS RECORD...",
    0xf841: "	-	Initiate Tape Read                                   ",
    0xf864: "	-	Initiate Tape Write                                  ",
    0xf875: "	-	Common Tape Code                                     ",
    0xf8d0: "	-	Check Tape Stop                                      ",
    0xf8e2: "	-	Set Read Timing                                      ",
    0xf92c: "	-	Read Tape Bits                                       ",
    0xfa60: "	-	Store Tape Characters                                ",
    0xfb8e: "	-	Reset Tape Pointer                                   ",
    0xfb97: "	-	New Character Setup                                  ",
    0xfba6: "	-	Send Tone to Tape                                    ",
    0xfbc8: "	-	Write Data to Tape                                   ",
    0xfbcd: "	-	IRQ Entry Point                                      ",
    0xfc57: "	-	Write Tape Leader                                    ",
    0xfc93: "	-	Restore Normal IRQ                                   ",
    0xfcb8: "	-	Set IRQ Vector                                       ",
    0xfcca: "	-	Kill Tape Motor                                      ",
    0xfcd1: "	-	Check Read / Write Pointer                           ",
    0xfcdb: "	-	Bump Read / Write Pointer                            ",
    0xfce2: "	-	Power-Up RESET Entry                                 ",
    0xfd02: "	-	Check For 8-ROM                                      ",
    0xfd12: "	-	8-ROM Mask '80CBM'			DATA                     ",
    0xfd15: "	restor	Restore Kernal Vectors (at 0314)                 ",
    0xfd1a: "	vector	Change Vectors For User                          ",
    0xfd30: "	-	Kernal Reset Vectors			WORD                 ",
    0xfd50: "	ramtas	Initialise System Constants                      ",
    0xfd9b: "	-	IRQ Vectors For Tape I/O		WORD                 ",
    0xfda3: "	ioinit	Initialise I/O                                   ",
    0xfddd: "	-	Enable Timer                                         ",
    0xfdf9: "	setnam	Set Filename                                     ",
    0xfe00: "	setlfs	Set Logical File Parameters                      ",
    0xfe07: "	readst	Get I/O Status Word                              ",
    0xfe18: "	setmsg	Control OS Messages                              ",
    0xfe21: "	settmo	Set IEEE Timeout                                 ",
    0xfe25: "	memtop	Read / Set Top of Memory                         ",
    0xfe34: "	membot	Read / Set Bottom of Memory                      ",
    0xfe43: "	-	NMI Transfer Entry                                   ",
    0xfe66: "	-	Warm Start Basic [BRK]                               ",
    0xfebc: "	-	Exit Interrupt                                       ",
    0xfec2: "	-	RS-232 Timing Table - NTSC	DATA                     ",
    0xfed6: "	-	NMI RS-232 In                                        ",
    0xff07: "	-	NMI RS-232 Out                                       ",
    0xff43: "	-	Fake IRQ Entry                                       ",
    0xff48: "	-	IRQ Entry                                            ",
    0xff5b: "	cint	Initialize screen editor                         ",
    0xff80: "		-	Kernal Version Number [03]	DATA                 ",
    0xff81: "Init Editor & Video Chips                  ",
    0xff84: "Init I/O Devices, Ports & Timers          ",
    0xff87: "Init Ram & Buffers                        ",
    0xff8a: "Restore Vectors                           ",
    0xff8d: "Change Vectors For User                   ",
    0xff90: "Control OS Messages                       ",
    0xff93: "Send SA After Listen                      ",
    0xff96: "Send SA After Talk                        ",
    0xff99: "Set/Read System RAM Top                   ",
    0xff9c: "Set/Read System RAM Bottom                ",
    0xff9f: "Scan Keyboard                             ",
    0xffa2: "Set Timeout In IEEE                       ",
    0xffa5: "Handshake Serial Byte In                  ",
    0xffa8: "Handshake Serial Byte Out                 ",
    0xffab: "Command Serial Bus UNTALK                 ",
    0xffae: "Command Serial Bus UNLISTEN               ",
    0xffb1: "Command Serial Bus LISTEN                 ",
    0xffb4: "Command Serial Bus TALK                   ",
    0xffb7: "Read I/O Status Word                      ",
    0xffba: "Set Logical File Parameters               ",
    0xffbd: "Set Filename                              ",
    0xffc0: "Open Vector [f34a]                        ",
    0xffc3: "Close Vector [f291]                       ",
    0xffc6: "Set Input [f20e]                          ",
    0xffc9: "Set Output [f250]                         ",
    0xffcc: "Restore I/O Vector [f333]                 ",
    0xffcf: "Input Vector, chrin [f157]                ",
    0xffd2: "Output Vector, chrout [f1ca]              ",
    0xffd5: "Load RAM From Device                      ",
    0xffd8: "Save RAM To Device                        ",
    0xffdb: "Set Real-Time Clock                       ",
    0xffde: "Read Real-Time Clock                      ",
    0xffe1: "Test-Stop Vector [f6ed]                   ",
    0xffe4: "Get From Keyboad [f13e]                   ",
    0xffe7: "Close All Channels And Files [f32f]       ",
    0xffea: "Increment Real-Time Clock                 ",
    0xffed: "Return Screen Organization                ",
    0xfff0: "Read / Set Cursor X/Y Position            ",
    0xfff3: "Return I/O Base Address                   ",

    0xA000: ":::  BASIC baby!!!",
}
